apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: elastic/kibana:7.17.23
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-svc:9200"
            - name: discovery.type
              value: single-node
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "elasticfk"
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-svc
  namespace: logging
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5601
    - protocol: TCP
      name: https
      port: 443
      targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer
