---
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx to forward port 8080 to 80
  copy:
    dest: /etc/nginx/sites-available/jenkins.paperple.o-r.kr
    content: |
      server {
        listen 80;
        server_name jenkins.paperple.o-r.kr;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name jenkins.paperple.o-r.kr;

        location / {
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  ignore_errors: yes

- name: Obtain Let's Encrypt certificate
  command: certbot --nginx -d jenkins.paperple.o-r.kr --agree-tos --non-interactive -m hnnynh125@gmail.com
  register: certbot_output
  changed_when: "'Congratulations' in certbot_output.stdout"

- name: Create symbolic link for Nginx site configuration
  file:
    src: /etc/nginx/sites-available/jenkins.paperple.o-r.kr
    dest: /etc/nginx/sites-enabled/jenkins.paperple.o-r.kr
    state: link

- name: Update nginx.conf to include specific site
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^include /etc/nginx/sites-enabled/\*;'
    line: "include /etc/nginx/sites-enabled/jenkins.paperple.o-r.kr;"
    state: present

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  ignore_errors: yes

- name: Reload Nginx to apply TLS
  service:
    name: nginx
    state: reloaded
  when: certbot_output.changed and nginx_test.rc == 0
